### ISSUE TITLE
HEX as default on fallback

### ISSUE THREAD

**Issue by dalholm** [saintplay/vue-swatches#69] opened 2021-03-22 07:26 UTC
Hello,
Is there a way to set HEX color as default instead of RGB ? 

<img width="265" alt="Screenshot 2021-03-22 at 08 23 45" src="https://user-images.githubusercontent.com/426083/111954293-27d13580-8ae8-11eb-895a-4361f6fe4b3b.png">

**Comment by saintplay** [comment] 2021-03-22 20:25
Hello,
duplicate of #56

**Closed by saintplay** 2021-03-22 20:25 UTC
